spring:
  config:
    import: optional:file:.env[.properties]
  cache:
    type: redis
    cache-names: redis-cache
  data:
    redis:
      host: localhost
      port: 6379
      password: ${REDIS_PASSWORD}
  datasource:
    url: jdbc:postgresql://localhost:5432/tasklist?currentSchema=tasklist
    username: postgres
    password: 442656827
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true
    default-schema: tasklist
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
security:
  jwt:
    access: 15 #минут
    refresh: 24 #часа
entity:
  task:
    max_length_title: 25
    max_length_description: 255
  pattern:
    forbidden_js_chars_pattern: "[<>&']"
    email_pattern: "^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$"


springdoc:
  override-with-generic-response: false