spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tasklist?currentSchema=tasklist
    username: postgres
    password: 442656827
  sql:
    init:
      mode: always
      continueOnError: false
 #     dataLocations: classpath:demo_data.sql
security:
   jwt:
     secret: YXNkdXdkYXNkdXlmYXd1ZGlhdXd1ZnVhZmFmaWF3ZnVGQVNGQVNmd2ZhZkFTRkFTRmFzZnF3ZHV5ZnF3dWZzZEZTREdBSEVSRldGU0FE
     access: 3600000
     refresh: 2592000000